# Generated by Django 5.1 on 2024-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
                ("isbn_number", models.CharField(max_length=13, unique=True)),
                ("number_of_pages", models.PositiveIntegerField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cover_image/"),
                ),
                ("language", models.CharField(max_length=50)),
            ],
        ),
    ]
