# Generated by Django 5.1 on 2024-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn_number",
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hardcover"), ("SOFT", "Softcover")],
                default="SOFT",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Daily fee in USD",
                max_digits=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
