# Generated by Django 5.1 on 2024-09-03 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_remove_book_isbn_number_book_cover_book_daily_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(
                help_text="Number of copies available (must be a positive integer).",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
